### ISSUE TITLE
OpenSSL v1.0 incompatibility and OPM common dependencies

### ISSUE THREAD

**Issue by billythedummy** [jie123108/lua-resty-s3#10]
**OpenResty Version**: 1.18.5.2
**OpenSSL Version**: 1.1.1g

Running `s3:put` in the abovementioned environment logs the following error:
```
lua entry thread aborted: runtime error: /usr/local/openresty/site/lualib/resty/hmac.lua:93: Symbol not found: HMAC_CTX_init
```

Secondly, the presence of external lua libraries in the package (hmac.lua, http.lua, etc) messes up opm when you have other opm packages that share these dependencies:

```
ERROR: file resty/hmac.lua in package jkeys089/lua-resty-hmac already appears in the previously installed package lua-resty-s3.
```

**Suggestion:** Remove all external library files and move them to the `requires` directive of dist.ini

**Comment by billythedummy** [comment]
nvm I see that you guys are aware of the issue in commit a8dfab2d9f8809d67d64fb67aefd656ce4de6ec5

**Comment by billythedummy** [comment]
I made a fork where I removed all external libraries and instead specify it as dependencies in `dist.ini`. I also did some refactoring to make the naming scheme more consistent (and hopefully avoid naming conflicts in the `resty/` folder) https://github.com/billythedummy/lua-resty-s3

 I've ran it a couple of times but have not tested it extensively, please let me know if you would like me to open a pull request so that you guys can take a look as well

**Comment by jie123108** [comment]
You're welcome to submit a PR, and I'll merge it in after testing.

**Comment by jie123108** [comment]
pr(#11) has been merged
