### ISSUE TITLE
How to install lua-resty-s3?

### ISSUE THREAD

**Issue by meetme2meat** [jie123108/lua-resty-s3#8]
I'm very new to Lua and I only know you get stuff using luarocks. But Lua-resty-s3 listed on luarocks is different than this.  What to do?

**Comment by jie123108** [comment]
1. download by git
git clone https://github.com/jie123108/lua-resty-s3
2. config lua_package_path
`lua_package_path '/path/to/lua-resty-s3/lib/?.lua;;';`
